trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  # Usa un agente hospedado por Microsoft

steps:
  # Paso 1: Compilar y ejecutar tests con Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package'
    displayName: 'Compilar y ejecutar tests con Maven'

  # Paso 2: Ejecutar la aplicación
  - script: |
      java -jar target/VitalApp-1.0-SNAPSHOT.jar
    displayName: 'Ejecutar la aplicación'

  # Paso 3: Publicar artefactos (JAR) generados
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'vitalapp-artifact'
    displayName: 'Publicar artefactos generados'
