trigger:
  - main

pool:
  vmImage: 'ubuntu-22.04'  # Imagen más estable

steps:
  - task: Maven@4  # Usando la versión más nueva de la tarea Maven
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean package'
    displayName: 'Compilar y ejecutar tests con Maven'

  # Ejecutar la aplicación (opcional, si tu JAR tiene un main)
  - script: |
      java -jar target/VitalApp-1.0-SNAPSHOT.jar
    displayName: 'Ejecutar la aplicación'

  # Publicar artefacto generado
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'vitalapp-artifact'
    displayName: 'Publicar artefactos generados'
