trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'  # usa el agente hospedado más reciente

steps:
  # Compilar el proyecto y ejecutar pruebas unitarias
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'  # Especifica la versión de JDK 17
      mavenOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
    displayName: 'Compilar y ejecutar pruebas con Maven'

  # Ejecutar la aplicación (si el .jar tiene un método main válido)
  - script: java -jar target/VitalApp-1.0-SNAPSHOT.jar
    displayName: 'Ejecutar la aplicación'

  # Publicar artefactos (JAR) generados
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'target'
      ArtifactName: 'vitalapp-artifact'
    displayName: 'Publicar artefactos generados'
